In [2]:
from pathlib import Path 
import pandas as pd 
 
DATA = Path('../datasets') 
orders = pd.read_csv(DATA / 'orders_raw.csv') 
riders = pd.read_csv(DATA / 'riders_raw.csv') 
stores = pd.read_csv(DATA / 'stores_raw.csv') 
 
print('Orders:', orders.shape) 
print('Riders:', riders.shape) 
print('Stores:', stores.shape)

Orders: (605, 13)
Riders: (30, 6)
Stores: (12, 6)

In [3]:
orders.head()

,order_id,order_ts,customer_zone,store_id,rider_id,item_count,basket_value,payment_mode,promised_minutes,delivered_minutes,delivery_status,customer_rating,refund_amount
0,ORD00001,2026-01-12 08:24:00,Kharadi,ST011,RD007,9,391,Cash,10,23.0,returned,1.0,150
1,ORD00002,2026-01-05 20:51:00,Koramangala,ST005,RD010,4,515,Card,35,43.0,delivered,4.0,0
2,ORD00003,2026-01-08 23:38:00,OMR,ST007,RD004,8,660,UPI,10,17.0,delivered,1.0,0
3,ORD00004,2026-01-02 21:41:00,Nizampet,ST003,RD006,8,303,Cash,30,41.0,delivered,4.0,0
4,ORD00005,2026-01-03 10:30:00,Whitefield,ST006,RD011,4,96,UPI,10,11.0,delivered,4.0,0

In [4]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           605 non-null    str
 1   order_ts           605 non-null    str
 2   customer_zone      605 non-null    str
 3   store_id           605 non-null    str
 4   rider_id           595 non-null    str
 5   item_count         605 non-null    int64
 6   basket_value       605 non-null    int64
 7   payment_mode       599 non-null    str
 8   promised_minutes   605 non-null    int64
 9   delivered_minutes  564 non-null    float64
 10  delivery_status    605 non-null    str
 11  customer_rating    551 non-null    float64
 12  refund_amount      605 non-null    int64
dtypes: float64(2), int64(4), str(7)
memory usage: 61.6 KB

In [5]:
orders.isna().sum()

order_id              0
order_ts              0
customer_zone         0
store_id              0
rider_id             10
item_count            0
basket_value          0
payment_mode          6
promised_minutes      0
delivered_minutes    41
delivery_status       0
customer_rating      54
refund_amount         0
dtype: int64

In [6]:
orders.duplicated(subset=['order_id']).sum()

np.int64(5)

In [7]:
orders['delivery_status'].value_counts(dropna=False)

delivery_status
delivered    521
cancelled     54
returned      30
Name: count, dtype: int64

In [1]:
import pandas as pd
import numpy as np

In [2]:
orders = pd.read_csv("../datasets/orders_raw.csv")
riders = pd.read_csv("../datasets/riders_raw.csv")
stores = pd.read_csv("../datasets/stores_raw.csv")

In [3]:
orders.head()
orders.shape
orders.info()
orders.describe()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           605 non-null    str
 1   order_ts           605 non-null    str
 2   customer_zone      605 non-null    str
 3   store_id           605 non-null    str
 4   rider_id           595 non-null    str
 5   item_count         605 non-null    int64
 6   basket_value       605 non-null    int64
 7   payment_mode       599 non-null    str
 8   promised_minutes   605 non-null    int64
 9   delivered_minutes  564 non-null    float64
 10  delivery_status    605 non-null    str
 11  customer_rating    551 non-null    float64
 12  refund_amount      605 non-null    int64
dtypes: float64(2), int64(4), str(7)
memory usage: 61.6 KB

,item_count,basket_value,promised_minutes,delivered_minutes,customer_rating,refund_amount
count,605.000000,605.000000,605.000000,564.000000,551.000000,605.000000
mean,9.985124,646.847934,21.842975,31.336879,3.949183,18.140496
std,5.154061,528.459363,8.580557,82.715782,1.141432,53.076433
min,1.000000,-100.000000,10.000000,-5.000000,1.000000,0.000000
25%,6.000000,297.000000,15.000000,16.000000,3.000000,0.000000
50%,10.000000,471.000000,20.000000,24.000000,4.000000,0.000000
75%,15.000000,775.000000,30.000000,34.000000,5.000000,0.000000
max,18.000000,2825.000000,35.000000,999.000000,5.000000,250.000000

In [4]:
orders.isnull().sum()

order_id              0
order_ts              0
customer_zone         0
store_id              0
rider_id             10
item_count            0
basket_value          0
payment_mode          6
promised_minutes      0
delivered_minutes    41
delivery_status       0
customer_rating      54
refund_amount         0
dtype: int64

In [5]:
riders.isnull().sum()

rider_id        0
rider_name      0
city            0
vehicle_type    0
joining_date    0
active_flag     0
dtype: int64

In [6]:
stores.isnull().sum()

store_id           0
city               0
store_area         0
store_type         0
cold_chain_flag    0
launch_date        0
dtype: int64

In [7]:
orders.duplicated().sum()

np.int64(5)

In [8]:
riders.duplicated().sum()
stores.duplicated().sum()

np.int64(0)

In [9]:
orders.dtypes
riders.dtypes
stores.dtypes

store_id           str
city               str
store_area         str
store_type         str
cold_chain_flag    str
launch_date        str
dtype: object

In [10]:
orders = orders.drop_duplicates()

In [11]:
orders.isnull().sum()
riders.isnull().sum()
stores.isnull().sum()

orders.duplicated().sum()
riders.duplicated().sum()
stores.duplicated().sum()

np.int64(0)

In [12]:
orders.to_csv("../outputs/orders_clean.csv", index=False)

riders.to_csv("../outputs/riders_clean.csv", index=False)

stores.to_csv("../outputs/stores_clean.csv", index=False)